### ISSUE TITLE
Cannot compile Cairo contracts after upgrading to latest version of ape-starknet

### ISSUE THREAD

**Issue by sanchopansa** [ApeWorX/ape-starknet#111]
### Environment information

* `ape` and plugin versions:

```
$ ape --version
0.5.1

$ ape plugins list
Installed Plugins:
  starknet    0.5.0a0
  cairo       0.5.0a0

$ pip freeze | ag ape-starknet
ape-starknet==0.5.0a0
```

* Python Version: 3.8.5
* OS: Ubuntu 20.04

### What went wrong?
In a brand new virtual environment, running Python 3.8.5, I installed `ape-starknet` using `pip install ape-starknet` and then installed the Cairo and StarkNet plugins with: `ape plugins install starknet cairo`. The last command showed an error during execution:

```
WARNING: Ecosystem 'starknet' is not a registered ecosystem.
INFO: Installing starknet...
SUCCESS: Plugin 'starknet==0.5.0a0' has been installed.
INFO: Installing cairo...
ERROR: ape-starknet 0.5.0a0 has requirement starknet.py==0.6.0a0, but you'll have starknet-py 0.6.1a0 which is incompatible.
SUCCESS: Plugin 'cairo==0.5.0a0' has been installed.
```

but the plugin appears to be successfully installed according to the output and also `ape plugins list`. I also noticed that there is no ape-cairo dependency inside the virtual environment following the installation of the plugin (not sure if that is an issue, but prior to this upgrade the package was installed):

```
$ pip freeze | ag ape
ape-starknet==0.5.0a0
eth-ape==0.5.1
```
Now, when I try to compile any Cairo smart contract, I get the following error:

```
$ ape compile contracts/Staking.cairo
INFO: Compiling 'Staking.cairo'.
Traceback (most recent call last):
  File "/home/sancho/.pyenv/versions/3.8.5/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ape_compile/_cli.py", line 53, in cli
    contract_types = cli_ctx.project_manager.load_contracts(
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ape/managers/project/manager.py", line 501, in load_contracts
    manifest = self._project.create_manifest(file_paths, use_cache=use_cache)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ape/managers/project/types.py", line 159, in create_manifest
    compiled_contract_types = self.compiler_manager.compile(list(needs_compiling))
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ape/managers/compilers.py", line 98, in compile
    compiled_contracts = self.registered_compilers[extension].compile(
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/site-packages/ape_cairo/compiler.py", line 119, in compile
    source = StarknetCompilationSource(str(contract_path))
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/typing.py", line 729, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/home/sancho/.pyenv/versions/3.8.5/lib/python3.8/typing.py", line 339, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Union
```

The same contract compiles using `starknet-compile` without errors.
### How can it be fixed?

**Comment by sanchopansa** [comment]
I am still unsure what is causing this in my development environment, but I tried installing ape-starknet and compiling on a fresh Ubuntu 20.04 VPS and it works as expected (no warning when installing the cairo plugin, ape-cairo is installed, compilation passes). Closing this.
