### ISSUE TITLE
Use Ape artifact for OZ account creation

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape-starknet#35]
### Overview

then we can delete the random `_deploy()` helper that is in the provider because it is a bit confusing!
Also it would be great way to showcase the SDK feature some more and show how we can include it with a plugin.

Or maybe just import the contract type dict.

### Specification

* Compile the OpenZeppelin account contract into a PackageManifest using Ape
* Include the manifest as an artifact of the ape-starknet plugin
* Deploy the accounts the aApe way in the Starknet accounts plugin!!!

### Dependencies

Include links to any open issues that must be resolved before this feature can be implemented.

**Comment by ca11ab1e** [comment]
Would that solve such issue?

```bash
$ ape starknet accounts create --network starknet:testnet MY_ALIAS
```
```python
INFO: Deploying an account to 'testnet' network ...
Enter a new passphrase: 
Repeat for confirmation: 
Traceback (most recent call last):
  File "/.../bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/.../site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/.../site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/.../site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/.../site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.../site-packages/ape/cli/commands.py", line 18, in invoke
    super().invoke(ctx)
  File "/.../site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.../site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/.../site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/.../site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/.../site-packages/ape_starknet/accounts/_cli.py", line 51, in create
    contract_address = container.deploy_account(alias, token=token)
  File "/.../site-packages/ape_starknet/accounts/__init__.py", line 216, in deploy_account
    self.import_account(alias, network_name, contract_address, key_pair.private_key)
  File "/.../site-packages/ape_starknet/accounts/__init__.py", line 178, in import_account
    new_account.write(passphrase=passphrase, private_key=private_key, deployments=deployments)
  File "/.../site-packages/ape_starknet/accounts/__init__.py", line 457, in write
    key_file_data = self.__encrypt_key_file(passphrase, private_key=private_key)
  File "/.../site-packages/ape_starknet/accounts/__init__.py", line 572, in __encrypt_key_file
    return create_keyfile_json(key_bytes, passphrase_bytes, kdf="scrypt")
  File "/.../site-packages/eth_keyfile/keyfile.py", line 39, in create_keyfile_json
    return _create_v3_keyfile_json(private_key, password, kdf, iterations)
  File "/.../site-packages/eth_keyfile/keyfile.py", line 128, in _create_v3_keyfile_json
    address = keys.PrivateKey(private_key).public_key.to_address()
  File "/.../site-packages/eth_keys/datatypes.py", line 251, in __init__
    validate_private_key_bytes(private_key_bytes)
  File "/.../site-packages/eth_keys/validation.py", line 89, in validate_private_key_bytes
    validate_bytes_length(value, 32, "private key")
  File "/.../site-packages/eth_keys/validation.py", line 54, in validate_bytes_length
    raise ValidationError(
eth_utils.exceptions.ValidationError: Unexpected private key length: Expected 32, but got 31 bytes
```

**Comment by 0xSidius** [comment]
given this recent PR about the availability of pre-deployed accounts in Ape: https://github.com/ApeWorX/ape-starknet/pull/41

and given the last release of devnet: https://github.com/Shard-Labs/starknet-devnet/releases/tag/v0.2.5

would it make sense to triangulate all 3 into a single account feature on Ape side?

**Comment by unparalleled-js** [comment]
hardcoded to OZ for now.
new ticket should be made for better supporting non-oz accounts
