### ISSUE TITLE
`No content to fetch` compile error

### ISSUE THREAD

**Issue by tevrat-aksoy** [ApeWorX/ape-starknet#88]
### Environment information

`ape compile`   fails after first compile completed with `No content to fetch.` error.

* `ape` and plugin versions:

```
$ ape --version
#  `0.4.4`

$ ape plugins list
Installed Plugins:
  starknet    0.4.0a0
  cairo       0.4.0a0
  solidity    0.4.0
  hardhat     0.4.1
```
* Python Version: Python 3.9.13
* OS: linux

### What went wrong?

After `ape compile` completed, other compile commands fails.

Please include information like:

*` ape compile`
```
Traceback (most recent call last):
  File "/home/tevrat/cairo_venv/bin/ape", line 8, in <module>
    sys.exit(cli())
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/ape/_cli.py", line 40, in invoke
    return super().invoke(ctx)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/ape_compile/_cli.py", line 53, in cli
    contract_types = cli_ctx.project_manager.load_contracts(
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/ape/managers/project/manager.py", line 505, in load_contracts
    manifest = self._project.create_manifest(file_paths, use_cache=use_cache)
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/ape/managers/project/types.py", line 137, in create_manifest
    needs_compiling = set(filter(does_need_compiling, source_paths))
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/ape/managers/project/types.py", line 126, in does_need_compiling
    cached_checksum = cached_source.calculate_checksum()
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/ethpm_types/source.py", line 143, in calculate_checksum
    content = self.fetch_content()
  File "/home/tevrat/cairo_venv/lib/python3.9/site-packages/ethpm_types/source.py", line 109, in fetch_content
    raise ValueError("No content to fetch.")
ValueError: No content to fetch.
```

Fill this in if you have ideas on how the bug could be fixed.

**Comment by 0xSidius** [comment]
bumping this

**Comment by unparalleled-js** [comment]
It seems like this issue should be in the `ape-cairo` repo

**Comment by tevrat-aksoy** [comment]
With `Ape Starknet 0.5.0a0` this issue is solved
